oro_menu_config:
    items:
        warehouse_tab:
            label: 'rockordier.warehouse.entity_label'
            uri: '#'
            extras:
                icon: icon-group
                position: 10

        warehouses_tab:
            label: 'rockordier.warehouse.entity_plural_label'
            route: 'rockordier_warehouse_index'
            extras:
                position: 5
                routes: ['rockordier_rockordier_*']
                description: 'rockordier.warehouse.description'

    tree:
        application_menu:
            children:
                warehouse_tab:
                    children:
                        warehouses_tab: ~

        shortcuts:
            children:
                warehouses_tab: ~

oro_titles:
    rockordier_warehouse_index: ~
    rockordier_warehouse_view: '%%warehouse%%'
    rockordier_warehouse_create: 'Create Waerehouse'
    rockordier_warehouse_update: '%%warehouse%% - Edit'