parameters:
  rockordier.warehouse.manager.class:            RocKordier\Bundle\FestivalWarehouseBundle\Entity\Manager\WarehouseManager
  rockordier.warehouse.entity.class:             RocKordier\Bundle\FestivalWarehouseBundle\Entity\Warehouse

services:
  rockordier.warehouse.manager:
    class: "%rockordier.warehouse.manager.class%"
    arguments:
      - "%%rockordier.warehouse.entity.class%"
      - "@doctrine.orm.entity_manager"
