sudo: false

language: php

php:
    - 5.4
    - 5.5
    - 5.6

env:
  - SYMFONY_VERSION=2.7.*

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - phpenv config-add travis.php.ini
  - travis_wait composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source --update-no-dev
  - travis_wait composer require squizlabs/php_codesniffer:2.3.3 --prefer-source --update-no-dev

script:
  - phpunit
  - ./vendor/bin/phpcs ./ -p --encoding=utf-8 --extensions=php --standard=psr2
